<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Platform_Promotion</name>
   <tag></tag>
   <elementGuidId>5bd57b54-21a2-4d6c-9f68-edfdab5b6c4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Promotion')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Promotion&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>23587045-6500-4439-9f47-73b01bb7051a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-secondary-18 hover:text-primary-1 text-xs md:text-sm font-medium transition-colors cursor-pointer</value>
      <webElementGuid>745a174b-1f3f-48e2-b1be-757a97341e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/desktop/promotion</value>
      <webElementGuid>dfc51cda-2ae1-4f4d-8903-10925519d383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Promotion</value>
      <webElementGuid>3a120d23-afc7-40ce-a43d-6620651c2c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;theme-nexus-alpha-dark-gold&quot;]/body[1]/div[@class=&quot;min-h-screen flex flex-col bg-background text-foreground&quot;]/footer[@class=&quot;bg-secondary-9 text-secondary-4 md:border-t-2 border-primary-7 py-5 text-sm leading-5.25&quot;]/div[@class=&quot;container mt-[15px]&quot;]/div[@class=&quot;border-y border-dotted border-secondary-5 py-3.75 md:border-t&quot;]/div[@class=&quot;grid grid-cols-2 gap-6.5 md:flex md:flex-row md:justify-between md:pr-10&quot;]/div[2]/ul[@class=&quot;space-y-2.5 pt-2.5 leading-5&quot;]/li[1]/a[@class=&quot;text-secondary-18 hover:text-primary-1 text-xs md:text-sm font-medium transition-colors cursor-pointer&quot;]</value>
      <webElementGuid>1ccef55b-ca31-4a0e-a674-eb1e3d872832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Promotion')]</value>
      <webElementGuid>0765e972-917d-4324-af2d-7bc5c9d1ef21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[1]/following::a[1]</value>
      <webElementGuid>9fa3f8de-8ba3-4383-ab56-cae65166b5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test EN'])[1]/following::a[1]</value>
      <webElementGuid>88048658-d8a2-4cdd-99f3-6e2373519805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loyalty'])[1]/preceding::a[1]</value>
      <webElementGuid>00fa45b8-3ee6-4cb3-ab53-7287e41d461f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referral'])[1]/preceding::a[1]</value>
      <webElementGuid>862444ca-492c-44ec-a1fc-3cc4788b294c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/desktop/promotion')])[2]</value>
      <webElementGuid>a7ed8fc0-a913-4e6e-b076-c7f5c1982f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>3f0945b9-cf29-4b1f-900d-070d67083957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/desktop/promotion' and (text() = 'Promotion' or . = 'Promotion')]</value>
      <webElementGuid>a2f38687-1bce-4a7e-9a79-19e15fde2c6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
