<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popular_Games_Play_Button</name>
   <tag></tag>
   <elementGuidId>abaf0394-d00a-4ad7-aa09-c67b11b4bffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'PLAY')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.play-now</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^PLAYMUSCLE FORTUNE CAT0$/ >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8b38f190-6ea8-4b04-932b-44c0ad459022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>play-now</value>
      <webElementGuid>c5ab8db6-413c-42bf-be53-8153520c0b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>77d428a8-de55-42be-b62a-53be8d345885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAY</value>
      <webElementGuid>e9e3f599-5526-497e-aa65-d71e7e8fdccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;theme-nexus-alpha-dark-gold&quot;]/body[1]/div[@class=&quot;min-h-screen flex flex-col bg-background text-foreground&quot;]/div[@class=&quot;flex flex-1 overflow-hidden&quot;]/main[@class=&quot;flex-1 overflow-auto bg-background&quot;]/div[@class=&quot;flex flex-col w-full h-auto&quot;]/div[@class=&quot;container&quot;]/section[@class=&quot;mb-3.75&quot;]/div[@class=&quot;border border-primary-4 p-2.5&quot;]/div[1]/div[@class=&quot;grid auto-cols-[calc((100%-30px)/6.5)] gap-x-[6px] gap-y-[10px] grid-flow-col overflow-x-auto native-scrollbar pb-0.75&quot;]/div[@class=&quot;group&quot;]/div[@class=&quot;relative overflow-hidden bg-[#141414] p-1.25&quot;]/div[@class=&quot;link-container absolute inset-0 flex flex-col items-center justify-center opacity-0 transition-opacity duration-200 group-hover:opacity-100&quot;]/a[@class=&quot;play-now&quot;]</value>
      <webElementGuid>a06946b1-daf0-4f66-bbff-e44a465cfb1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PLAY')]</value>
      <webElementGuid>7f895a0d-4389-49c5-82ba-e2197943b795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular Games'])[1]/following::a[1]</value>
      <webElementGuid>b29bcff3-cf77-421b-8852-ab2a891495c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Draw Sun, 04-Oct-2026 07:00:00'])[1]/following::a[1]</value>
      <webElementGuid>867ae53d-d7f1-436a-af4c-78cbc8b60b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUSCLE FORTUNE CAT'])[1]/preceding::a[1]</value>
      <webElementGuid>fc625fbd-88f5-4dfe-88a4-efa7d6ee6464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wukong - Black Scatter'])[1]/preceding::a[2]</value>
      <webElementGuid>62897f88-3646-4737-8089-577c43f79791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PLAY']/parent::*</value>
      <webElementGuid>17ee4de0-838c-40b0-ad40-1159c8be4122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[15]</value>
      <webElementGuid>854a705e-4c0a-46fc-a3f8-49781b3772b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/a</value>
      <webElementGuid>57927fbf-cab5-42c0-b18d-efc0bebdeb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'PLAY' or . = 'PLAY')]</value>
      <webElementGuid>1746cfb6-4aad-4985-b8ea-4398d93a1815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
