<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Header_Language_Option_English</description>
   <name>Header_Language_Option_English</name>
   <tag></tag>
   <elementGuidId>8f12a34b-5678-4ef0-9821-123456789019</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[.//span[text()='ENGLISH']]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button:has(span)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
