<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Header_Sports_Button</description>
   <name>Header_Sports_Button</name>
   <tag></tag>
   <elementGuidId>fa2d2c16-95c2-4bd6-b369-2f828a0d7bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href='/desktop/sport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[href='/desktop/sport']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
