<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Login_Username_Input</description>
   <name>Login_Username_Input</name>
   <tag></tag>
   <elementGuidId>fa2d2c16-95c2-4bd6-b369-2f828a0d7bd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name='username']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
