<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popular_Video_Slots_Play_Button</name>
   <tag></tag>
   <elementGuidId>8758cf59-de8e-4d85-bbca-cc15e2d6b775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-7']/div/div/div/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.game-wrapper.relative > div.link-container > a.play-now</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.game-wrapper > .link-container > .play-now >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>40d103c2-e19f-41cb-9554-2a175f51ca98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>play-now</value>
      <webElementGuid>e8719395-577e-453a-bc8c-9df6894b3f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>80f36bda-8db6-458e-82c6-c840e2129842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>838c75fb-25c6-4f87-a861-6c12aaa113f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-7&quot;)/div[@class=&quot;popular-game-list&quot;]/div[@class=&quot;game-item&quot;]/div[@class=&quot;game-wrapper relative&quot;]/div[@class=&quot;link-container&quot;]/a[@class=&quot;play-now&quot;]</value>
      <webElementGuid>9e1bb79c-cdd0-4ca6-8697-5e424c3c1148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-7']/div/div/div/div[2]/a[2]</value>
      <webElementGuid>fd44bc86-e442-40d2-8100-9fa8d3d8c40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Play')])[2]</value>
      <webElementGuid>a8df6679-5ce5-4c79-aa73-444827c86bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRY'])[1]/following::a[1]</value>
      <webElementGuid>47ae5a32-0955-4cbc-a97f-5a525aba482b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deep Sea Frenzy'])[1]/following::a[3]</value>
      <webElementGuid>074b8836-a8ce-44e2-b577-0d5d8cdff66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRY'])[2]/preceding::a[1]</value>
      <webElementGuid>86727274-094f-4ba3-b952-f87b816edc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRY'])[3]/preceding::a[3]</value>
      <webElementGuid>0f31d2a1-df0a-44be-8d4f-666100b92cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[35]</value>
      <webElementGuid>d1a4c36f-9eab-4295-83d5-757863bf000c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/a[2]</value>
      <webElementGuid>0ab5b603-6d98-42de-b531-047bb7f19b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Play' or . = 'Play')]</value>
      <webElementGuid>5b5b1b7e-3b8d-4a18-b485-241d71ba2c56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
